version: '3.9'
services:
  storageapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storageapi
    restart: always
    ports:
      - "5068:5068"
    environment:
      - ASPNETCORE_URLS=http://+:5068
    networks:
      - storage_network  
  storage_nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: storage_nginx
    ports:
      - "8443:8443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - storage_network

networks:
  storage_network:
    driver: bridge